'use client';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Printer,Check,CalendarDays,FileText} from 'lucide-react';
export type AutomaticIssue={slug:string;cutoff:string;through:string;generatedAt:number;version:number;body:string;coverage:string[]};
function dateLabel(raw:string){return new Date(raw+'Z').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',timeZone:'UTC'});}
function timeLabel(raw:string){return new Date(raw+'Z').toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'UTC'});}
export default function AutomaticPaper({issue}:{issue:AutomaticIssue}){
 const content=JSON.parse(issue.body) as {title:string;method:string;items:{title:string;date:string;location:string;source:string;body:string;checkedAt:number}[]};
 const stale=Date.now()-issue.generatedAt>8*24*3600000;
 const endDate=new Date(issue.through+'T12:00:00Z');endDate.setUTCDate(endDate.getUTCDate()-1);const inclusiveEnd=endDate.toLocaleDateString('en-US',{month:'long',day:'numeric',timeZone:'UTC'});
 return <><div className="edition-tools"><Link className="text-link" href="/edition-preview">First design edition <ArrowRight size={16}/></Link><button className="outline-button" onClick={()=>window.print()}><Printer size={16}/>Print this edition</button></div><div className="edition-heading"><span className="kicker">THE MATCHSTICK · AUTOMATIC EDITION</span><h1>The week<br/><em>ahead.</em></h1><p>{dateLabel(issue.cutoff+'T00:00:00')}, {issue.cutoff.slice(0,4)}</p><span>Original city-calendar records. Meetings through {inclusiveEnd}. Version {issue.version}.</span><div className="automatic-badge"><Check size={14}/>Original records · Independently published</div></div>{stale&&<div className="coverage-banner"><strong>This edition is older than a week.</strong><p>The local backend may have stopped. Consult the original records for current information.</p></div>}<div className="edition-body"><section className="automatic-intro"><CalendarDays size={22}/><div><h2>A few dates worth knowing.</h2><p>{content.items.length?`${content.items.length} scheduled city events in this edition. All times are Wadsworth local time. A scheduled meeting does not establish a decision or vote.`:'Current events could not be established from a fresh official source. That is a coverage gap, not a claim that nothing is happening.'}</p></div></section>{content.items.map((item)=><article key={item.source}><span className="kicker">{dateLabel(item.date)} · {timeLabel(item.date)}</span><h2>{item.title}</h2><p>{item.location}. See the city’s original notice for participation details and schedule changes.</p><a className="automatic-source" href={item.source} target="_blank" rel="noopener noreferrer"><FileText size={14}/>Original city notice<ArrowUpRight size={14}/></a><small className="automatic-verification">Collected {new Date(item.checkedAt).toLocaleString('en-US',{timeZone:'America/New_York',dateStyle:'medium',timeStyle:'short'})} · America/New_York</small></article>)}<section className="coverage-banner"><span className="kicker">Coverage, in plain sight</span><h3>What this edition knows.</h3>{issue.coverage.map(note=><p key={note}>{note}</p>)}<p>{content.method}</p><Link className="text-link" href="/sources">See the source register <ArrowRight size={16}/></Link></section><div className="edition-end"><Link className="text-link" href={'/editions/'+issue.slug}>Permanent link to this edition <ArrowRight size={16}/></Link><h3>Fresh records. The same standard.</h3><p>Collected daily. Published weekly. Original versions preserved. This first working automation covers the city calendar; more source adapters are still being built.</p></div></div></>;
}
