'use client';
import {useEffect,useState} from 'react';
import {Search,Plus} from 'lucide-react';
import state from '../lib/legislation-snapshot.json';
import hutson from '../lib/hutson-legislation-snapshot.json';
import federal from '../lib/federal-legislation-snapshot.json';
type Step={label:string;done:boolean;date?:string};
type Bill={bill:string;title:string;url:string;representative:string;status:string;milestones:Step[];actions:{date?:string;text:string}[];summary?:string;version?:string;collectedAt:string;stale:boolean};
const date=(s:string)=>new Date(s.slice(0,10)+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const stateBills:Bill[]=[...state.records,...hutson.records as typeof state.records].map(r=>{
 const done=new Set(r.completedSteps),final=r.finalStage,signed=final.completed&&/Signed By The Governor/i.test(final.label),received=final.completed&&/Sent To The Governor|Signed By The Governor/i.test(final.label);
 const senate=done.has('Passed By Senate'),house=done.has('Passed By House');
 const origin=r.representative==='Sean Hutson'?'House':'Senate',other=origin==='House'?'Senate':'House';
 const status=origin==='House'?received?(signed?'Signed into law':'With the governor'):house&&senate?'Both chambers passed · final action pending':senate?'Passed Senate · final action pending':done.has('In Senate Committee')?'In Senate committee':house?'Passed House · awaiting Senate action':done.has('House committee reported the bill')?'Ready for House consideration':done.has('In House Committee')?'In House committee':'Introduced in the House':final.completed&&/veto/i.test(final.label)?'Vetoed by the governor':signed?'Signed into law':received?'With the governor':house&&senate?'Both chambers passed · final action pending':done.has('House committee reported the bill')?'Ready for House consideration':done.has('In House Committee')?'In House committee':senate?'Passed Senate · awaiting House action':done.has('Senate committee reported the bill')?'Ready for Senate consideration':done.has('In Senate Committee')?'In Senate committee':'Introduced in the Senate';
 return {...r,status,collectedAt:origin==='House'?hutson.collectedAt:state.collectedAt,stale:(origin==='House'?hutson.status:state.status)!=='ok',milestones:[{label:'Introduced',done:done.has('Introduced In '+origin)},{label:origin+' passed',done:origin==='House'?house:senate},{label:other+' passed',done:other==='House'?house:senate},{label:'Governor',done:received},{label:'Signed',done:signed}],actions:[...r.completedSteps.map(text=>({text})),...(final.completed?[{text:final.label}]:[])]};
});
const federalBills:Bill[]=federal.groups.flatMap(g=>g.records.map(r=>({...r,collectedAt:g.collectedAt,stale:g.status!=='ok'})));
const allBills=[...stateBills,...federalBills];
const people=['Mark Romanchuk','Sean Hutson','Max Miller','Bernie Moreno','Jon Husted'];
export default function BillTracker(){
 const [person,setPerson]=useState('Everyone'),[query,setQuery]=useState('');
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get('representative');if(p&&people.includes(p))setPerson(p);},[]);
 const bills=allBills.filter(r=>(person==='Everyone'||r.representative===person)&&`${r.bill} ${r.title} ${r.status} ${r.representative}`.toLowerCase().includes(query.toLowerCase()));
 function choose(value:string){setPerson(value);const url=new URL(window.location.href);if(value==='Everyone')url.searchParams.delete('representative');else url.searchParams.set('representative',value);window.history.replaceState(null,'',url);}
 return <section className="legislation-tracker"><div className="bill-controls"><label>Who’s proposing it?<select value={person} onChange={e=>choose(e.target.value)}><option>Everyone</option>{people.map(p=><option key={p}>{p}</option>)}</select></label><label className="project-search"><Search size={18}/><input aria-label="Search sponsored bills" placeholder="Try health, schools, tax…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="small-note">{bills.length} sponsored bills · Ohio’s 136th General Assembly and the 119th Congress. Blue marks show completed steps; they are not a prediction of passage.</p><div className="legislation-list">{bills.map(r=><details key={r.representative+r.bill}><summary><span className="kicker">{r.bill} · {r.representative}</span><strong>{r.title}</strong><Plus className="bill-expand" size={18}/><span className="bill-progress"><span className="bill-status">{r.status}</span><span className="bill-milestones" role="list" aria-label="Legislative milestones">{r.milestones.map(s=><span role="listitem" key={s.label} className={s.done?'milestone-complete':''}><span className="milestone-track" aria-hidden="true"/><span>{s.label}<span className="sr-only">{s.done?' · completed':' · not completed'}{s.date?' '+date(s.date):''}</span></span></span>)}</span></span></summary><p>{r.representative} is a primary sponsor.{r.version&&<> Current version: <strong>{r.version}</strong>.</>}</p>{r.summary&&<div className="bill-summary"><h3>What the bill would do</h3><p>{r.summary}</p><small>Congressional Research Service summary · provisions can change as a bill advances.</small></div>}<h3>Recorded actions</h3><ol className="bill-steps">{r.actions.map((a,i)=><li key={i}>{a.date&&<time>{date(a.date)} · </time>}{a.text}</li>)}</ol><details className="tool-evidence"><summary>Source & update</summary><p>Checked {date(r.collectedAt)}. Primary sponsors only; cosponsored bills, amendments and resolutions are excluded. A bill may return to an earlier chamber for amendments. The markers show recorded passage, not approval of identical final text.</p><a href={r.url} target="_blank" rel="noopener noreferrer">Official bill text & history ↗</a>{r.stale&&<p>This is the last successful snapshot; newer actions may be missing.</p>}</details></details>)}</div>{person==='Sean Hutson'&&<p>As of {date(hutson.collectedAt)}, Hutson’s official House profile lists no primary-sponsored bills. He was appointed September 30, 2026.</p>}{!bills.length&&person!=='Sean Hutson'&&<p>No sponsored bills match that search.</p>}</section>;
}
