'use client';
import {useRef,useState} from 'react';
import Image from 'next/image';
import {Search,Plus,Minus,MapPin} from 'lucide-react';
import permits from '../lib/permit-snapshot.json';
import legislation from '../lib/legislation-snapshot.json';
const asset=(p:string)=>(process.env.NEXT_PUBLIC_BASE_PATH||'')+p;
const date=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const types:Record<string,string>={'COMMERCIAL-NEW CONSTRUCTN':'New commercial building','COMMERCIAL-REMODEL':'Commercial remodel','EXISTING BLDG C OF O':'Existing-building occupancy certificate','ALARM SYSTEM':'Alarm system','COMM-GENERATOR':'Generator','COMMERCIAL HVAC':'Heating & cooling work'};
export function WardMap(){const [zoom,setZoom]=useState(1);const mapRef=useRef<HTMLDivElement>(null);return <details className="ward-map-tool" onToggle={e=>{if(e.currentTarget.open&&mapRef.current)mapRef.current.scrollTop=mapRef.current.clientWidth*.25;}}><summary>Find my ward on the map <MapPin size={18}/></summary><p>Find your street in the colored area, then choose that ward above to see your council member. City boundaries differ from a Wadsworth mailing address.</p><div className="map-toolbar"><button className="outline-button" onClick={()=>setZoom(Math.max(1,zoom-0.5))} disabled={zoom===1} aria-label="Zoom ward map out"><Minus size={18}/></button><span>{Math.round(zoom*100)}%</span><button className="outline-button" onClick={()=>setZoom(Math.min(4,zoom+0.5))} disabled={zoom===4} aria-label="Zoom ward map in"><Plus size={18}/></button><span>Scroll to move around the map.</span></div><div ref={mapRef} className="ward-map-scroll" tabIndex={0} aria-label="Official ward map, scroll to explore"><div style={{width:`${zoom*100}%`}}><Image src={asset('/ward-map-2026.png')} width={1671} height={2600} alt="Official February 2026 Wadsworth ward map: Ward 1 green, Ward 2 orange, Ward 3 blue, Ward 4 purple, with labeled streets." unoptimized/></div></div><p className="small-note">City of Wadsworth · February 2026 ward map. For addresses on a boundary, confirm your ward with the Medina County Board of Elections.</p></details>;}
export function PermitBoard({compact=false}:{compact?:boolean}){const [query,setQuery]=useState(''),[filter,setFilter]=useState('Major work');const records=permits.records.filter(p=>(filter==='All work'||['COMMERCIAL-NEW CONSTRUCTN','COMMERCIAL-REMODEL','EXISTING BLDG C OF O'].includes(p.type))&&`${p.address} ${types[p.type]||p.type} ${p.id}`.toLowerCase().includes(query.toLowerCase()));return <section className="permit-board" id="permits"><div className="section-title"><h2>{compact?'On the construction radar.':'What work is approved near you?'}</h2></div><p>Commercial permits · {date(permits.periodStart)}–{date(permits.periodEnd)} · Wadsworth city</p>{!compact&&<><label className="project-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a street, address or permit…" aria-label="Search commercial permits"/></label><div className="filter-tabs">{['Major work','All work'].map(f=><button key={f} className={filter===f?'selected':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div></>}<div className="permit-grid">{records.slice(0,compact?2:records.length).map(p=><article key={p.id}><span className="kicker">{types[p.type]||p.type}</span><h3>{p.address.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}</h3><p>Permit issued {date(p.issued)}{p.value>0&&<> · Estimated work value {new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(p.value)}</>}</p>{!compact&&<details><summary>See the permit details</summary><dl className="permit-facts"><div><dt>Permit</dt><dd>{p.id}</dd></div><div><dt>Work</dt><dd>{types[p.type]||p.type}</dd></div><div><dt>Related permits</dt><dd>{p.work.join(' · ')}</dd></div>{p.parcel&&<div><dt>Parcel</dt><dd>{p.parcel}</dd></div>}</dl></details>}</article>)}</div>{records.length===0&&<p>No matching permits in this report.</p>}<p className="small-note">A construction permit describes authorized work. It does not establish the business moving in or its opening day. Estimated value is not a contract price.</p>{!compact&&<details className="tool-evidence"><summary>Report & coverage</summary><p>Medina County Building Department · collected {date(permits.collectedAt.slice(0,10))}. Commercial work inside city boundaries; residential work and Wadsworth Township are excluded. Related permit entries are combined by permit number.</p><a href={permits.sourceUrl} target="_blank" rel="noopener noreferrer">Original county report ↗</a>{permits.status!=='ok'&&<p>This is the last successful report; newer records may be missing.</p>}</details>}</section>;}
type BillRecord={bill:string;title:string;url:string;version:string;completedSteps:string[];finalStage?:{label:string;completed:boolean}};
function billProgress(record:BillRecord){
 const done=new Set(record.completedSteps),final=record.finalStage;
 const signed=!!final?.completed&&/Signed By The Governor/i.test(final.label);
 const received=!!final?.completed&&/Sent To The Governor|Signed By The Governor/i.test(final.label);
 const vetoed=!!final?.completed&&/veto/i.test(final.label);
 const senate=done.has('Passed By Senate'),house=done.has('Passed By House');
 const milestones=[{label:'Introduced',done:done.has('Introduced In Senate')},{label:'Senate passed',done:senate},{label:'House passed',done:house},{label:'Governor',done:received},{label:'Signed',done:signed}];
 const status=vetoed?'Vetoed by the governor':signed?'Signed into law':received?'With the governor':house&&senate?'Both chambers passed · final action pending':done.has('House committee reported the bill')?'Ready for House consideration':done.has('In House Committee')?'In House committee':senate?'Passed Senate · awaiting House action':done.has('Senate committee reported the bill')?'Ready for Senate consideration':done.has('In Senate Committee')?'In Senate committee':'Introduced in the Senate';
 return {milestones,status,vetoed};
}
function BillProgress({record}:{record:BillRecord}){
 const progress=billProgress(record);
 return <span className="bill-progress"><span className={`bill-status${progress.vetoed?' bill-status-stopped':''}`}>{progress.status}</span><span className="bill-milestones" role="list" aria-label="Legislative milestones">{progress.milestones.map(step=><span role="listitem" key={step.label} className={step.done?'milestone-complete':''}><span className="milestone-track" aria-hidden="true"/><span>{step.label}<span className="sr-only">{step.done?' · completed':' · not completed'}</span></span></span>)}</span></span>;
}
export function LegislationTracker(){const [q,setQ]=useState('');const records=legislation.records.filter(r=>`${r.bill} ${r.title} ${billProgress(r).status}`.toLowerCase().includes(q.toLowerCase()));return <section className="legislation-tracker"><div className="section-title"><h2>What’s on Romanchuk’s desk?</h2></div><p>Bills your state senator has introduced · {legislation.assembly}. Follow each bill from introduction to signature.</p><p className="small-note">Checked {date(legislation.collectedAt.slice(0,10))}. Blue marks show the steps completed. Expand a bill for its history.</p><label className="project-search"><Search size={18}/><input aria-label="Search sponsored bills" placeholder="Try health, tax, energy…" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="legislation-list">{records.map(r=><details key={r.bill}><summary><span className="kicker">{r.bill}</span><strong>{r.title}</strong><Plus className="bill-expand" size={18}/><BillProgress record={r}/></summary><p>Mark Romanchuk is a primary sponsor. Current bill version: <strong>{r.version}</strong>.</p>{r.completedSteps.length>0&&<ol className="bill-steps">{r.completedSteps.map((step,i)=><li key={i}>{step}</li>)}{'finalStage' in r&&(r.finalStage as {completed:boolean;label:string})?.completed&&<li>{(r.finalStage as {label:string}).label}</li>}</ol>}<details className="tool-evidence"><summary>Original record</summary><p>Ohio Senate · sponsorship and bill status collected {date(legislation.collectedAt.slice(0,10))}.</p><a href={r.url} target="_blank" rel="noopener noreferrer">Bill text & history ↗</a>{legislation.status!=='ok'&&<p>The latest refresh failed. This is the last successful snapshot; newer actions may be missing.</p>}</details></details>)}</div>{!records.length&&<p>No sponsored bills match that search.</p>}</section>;}
