'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Search} from 'lucide-react';
import archive from '../lib/story-archive.json';
import rawEditions from '../lib/published-editions.json';
const editions=rawEditions as {slug:string;cutoff:string;kind:string;stories:unknown[]}[];
const date=(s:string)=>new Date(s.slice(0,10)+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
export function StoryArchive(){const [q,setQ]=useState(''),[topic,setTopic]=useState('All topics'),[month,setMonth]=useState('All dates');const months=['All dates',...new Set(archive.map(s=>s.editorial.eventDate?.slice(0,7)).filter(Boolean))].sort().reverse();const topics=['All topics',...new Set(archive.map(s=>s.category))];const result=archive.filter(s=>(month==='All dates'||s.editorial.eventDate?.startsWith(month))&&(topic==='All topics'||s.category===topic)&&`${s.title} ${s.dek} ${s.body}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));return <><div className="page-heading"><span className="kicker">The town, on the record</span><h1>Keep the story.</h1><p>A useful thing to know doesn’t vanish when the next paper arrives.</p></div><label className="project-search"><Search size={18}/><input aria-label="Search story archive" placeholder="A street, a school, a project…" value={q} onChange={e=>setQ(e.target.value)}/></label><label className="archive-date-filter">Development date <select value={month} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m} value={m}>{m==='All dates'?m:new Date(m+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</option>)}</select></label><div className="filter-tabs">{topics.map(t=><button key={t} aria-pressed={topic===t} className={topic===t?'selected':''} onClick={()=>setTopic(t)}>{t}</button>)}</div><div className="story-archive-grid">{result.map(s=><article className="story-card" key={s.slug}><span className="kicker">{s.category}</span><Link href={'/stories/'+s.slug}><h3>{s.title}</h3></Link><p>{s.dek}</p><small>{s.editorial.eventDate?'Development: '+date(s.editorial.eventDate)+' · ':''}Updated {date(s.updatedAt)}</small><Link className="text-link" href={'/stories/'+s.slug}>Read the story <ArrowRight size={16}/></Link></article>)}</div><EditionArchive/></>;}
export function EditionArchive(){return <section className="edition-archive"><h2>The back issues.</h2>{editions.map(e=><Link className="edition-archive-row" href={'/editions/'+e.slug} key={e.slug}><span><strong>{date(e.cutoff)}</strong><small>{e.kind==='catch-up'?'The catch-up edition':'Matchstick edition'} · {e.stories.length} stories</small></span><ArrowRight size={18}/></Link>)}</section>;}
export function StoryPage({slug}:{slug:string}){const s=archive.find(s=>s.slug===slug);if(!s)return null;return <><div className="breadcrumb"><Link href="/stories">Story archive</Link><span>/</span>{s.category}</div><article className="permanent-story"><span className="kicker">{s.category}</span><h1>{s.title}</h1><p className="lead-dek">{s.dek}</p><p className="story-dateline">Published {date(s.publishedAt)}{s.updatedAt!==s.publishedAt?' · Updated '+date(s.updatedAt):''}{s.editorial.eventDate?' · Development: '+date(s.editorial.eventDate):''}</p>{'correctionNote' in s&&Boolean(s.correctionNote)&&<p className="reader-note">Correction: {String(s.correctionNote)}</p>}{s.body.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}{'projectSlug' in s&&<Link className="text-link" href={'/projects/'+s.projectSlug}>Follow this project’s history <ArrowRight size={16}/></Link>}<details className="tool-evidence"><summary>The receipts</summary>{s.evidenceRefs.map((r,i)=><div key={i}><p>{r.assertion}</p>{'transcription' in r&&r.transcription==='ocr'&&<small>Scanned-page transcription</small>}{r.quote&&<blockquote>{r.quote}</blockquote>}<a href={r.url+'#page='+r.page} target="_blank" rel="noopener noreferrer">{r.owner} · page {r.page} ↗</a></div>)}</details>{s.versions.length>1&&<details className="tool-evidence"><summary>Updates to this story</summary>{s.versions.slice().reverse().map(v=><div key={v.versionHash}><strong>{date(v.savedAt)} · {v.title}</strong>{v.versionHash!==s.versions.at(-1)?.versionHash&&<p>{v.body}</p>}</div>)}</details>}<Link className="text-link" href="/stories">More from around town <ArrowRight size={16}/></Link></article></>;}
